sudo: required
services:
  - docker

before_install:
  - docker build -t dkrants/docker-react -f Dockerfile.dev .

script:
  - docker run dkrants/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-021666696166"
  bucker_path: "docker-react"
    on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
